# Basics
vo=gpu-next
gpu-api=vulkan
gpu-context=waylandvk
profile=high-quality

# Hardware Decoding
hwdec=auto
hwdec-extra-frames=10
hwdec-codecs=all

# Cache
demuxer-max-bytes=200MiB
demuxer-max-back-bytes=100MiB
cache-pause-initial=yes
prefetch-playlist=yes

# HDR
target-colorspace-hint=yes
hdr-compute-peak=yes
hdr-contrast-recovery=0.45
target-contrast=inf
target-peak=1000
target-trc=pq
inverse-tone-mapping
tone-mapping=bt.2390
tone-mapping-param=1.0

# Scaling
scale=ewa_lanczos4sharpest

# Seeking
hr-seek=yes
hr-seek-framedrop=no

# Smoothness
interpolation
video-sync=display-resample
tscale-blur=0.7

# Dither
dither=fruit
temporal-dither=yes

# Deband
deband=yes

# Audio
volume=50
audio-channels=auto
audio-file-auto=fuzzy
af=lavfi=[dynaudnorm=f=250:g=31:p=0.5:m=5:r=0.9:b=1]

# Playback
keep-open=yes
keep-open-pause=no
idle=yes
force-seekable=yes
watch-later-options=start
directory-filter-types=video,audio,archive,playlist
autocreate-playlist=filter
