
# BEGIN_KITTY_FONTS
font_family      family="Hurmit Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14.0
# END_KITTY_FONTS

# KEYKOARD SHORTCUTS
map ctrl+space new_window
map ctrl+n new_os_window
map ctrl+t new_tab
map ctrl+shift+space close_window
map ctrl+w close_tab
map cmd+] next_window
map cmd+[ previous_window
map cmd+r move_window_forward
map cmd+alt+[ previous_tab
map cmd+alt+] next_tab
map ctrl+left resize_window narrower
map ctrl+right resize_window wider
map ctrl+up resize_window taller
map ctrl+down resize_window shorter
# CURSOR
cursor_shape block
shell_integration no-cursor
cursor_blink_interval 0.5 ease-in-out
cursor_stop_blinking_after 15.0
cursor_trail 1

# MOUSE
mouse_hide_wait -1

# PERFORMANCE
repaint_delay 5

# BELL
bell_on_tab "* "
enable_audio_bell no
# LAYOUT
hide_window_decorations no

# TAB BAR
tab_bar_edge top
tab_bar_min_tabs 2
tab_bar_style powerline
tab_powerline_style angled
tab_bar_align left
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.progress_percent}{tab.active_exe}"
active_tab_foreground   #fff
active_tab_background   #399eb4
active_tab_font_style   bold
inactive_tab_foreground #444
inactive_tab_background #121221
inactive_tab_font_style normal

# COLOR SCHEME
foreground #fcfcfc
background #121212
background_opacity 0.55
background_blur 2
selection_foreground none
selection_background none

# ADVANCED
wayland_enable_ime no
wayland_titlebar_color system
