Counter=4

[Command_1]
Command=set include "/home/genty/.config/mpv/mpv.conf"
Order=0
OsdMessage=
Type=startup

[Command_3]
Command=set include "/home/genty/mpv/input.conf"
Order=1
OsdMessage=
Type=startup
