[Audio]
Volume=50

[General]
ColorScheme=Default
FloatingFooterTrigger=BottomMouseMovement
FooterStyle=floating
LastPlayedFile=file:///home/genty/Home_Server/Watch/Why Did PS1 Games Look Like That？ %5By84bG19sg6U%5D.mkv
ShowPreviewThumbnail=true
UseSingleInstance=true

[Playback]
YtdlFormat=bestvideo+bestaudio/best

[Playlist]
PlaybackBehavior=StopAfterItem

[Subtitles]
FontFamily=Hurmit Nerd Font
