[Audio]
Volume=60

[General]
ColorScheme=Default
FileDialogLastLocation=file:///home/genty/Archive/Videos/W40K
FloatingFooterTrigger=BottomMouseMovement
FooterStyle=floating
LastPlayedFile=https://www.youtube.com/watch?v=onVhbeY7nLM
ShowPreviewThumbnail=true
