[Application]
locale=C

[Backup]
location=/home/genty/.local/share/ghostwriter/backups/

[FindReplace]
highlightMatches=false
matchCase=false
regularExpression=false
wholeWord=false

[LastOpenedFile]
cursorPosition=757

[Preview]
codeFont="Hurmit Nerd Font Mono,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
htmlPreviewOpen=true
lastUsedExporter=cmark-gfm
lastUsedExporterParams=
textFont="Hurmit Nerd Font,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"

[Save]
autoSave=true
backupFile=true

[Session]
favoriteStatistic=0
rememberFileHistory=true
restoreSession=true

[Spelling]
liveSpellCheck=true

[Style]
blockquoteStyle=false
darkModeEnabled=false
displayTimeInFullScreen=true
editorFont="Hurmit Nerd Font,12,-1,5,300,0,0,0,0,0,0,0,0,0,0,1,Light"
editorWidth=1
focusMode=1
hideMenuBarInFullScreenEnabled=true
interfaceStyle=1
largeHeadings=true
theme=Classic
underlineInsteadOfItalics=false

[Tabs]
insertSpacesForTabs=false
tabWidth=4

[Typing]
autoMatchEnabled=true
autoMatchFilter=\"'([{*_`<
bulletPointCyclingEnabled=true

[Window]
mainWindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\x1\0\0\0\x19\0\0\x5V\0\0\x2\x31\0\0\0\x1\0\0\0\x19\0\0\x5V\0\0\x2\x31\0\0\0\0\0\0\0\0\a\x80\0\0\0\x1\0\0\0\x19\0\0\x5V\0\0\x2\x31)
mainWindowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x5V\0\0\x1\xf7\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)
sidebarOpen=false
splitterGeometry=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x3\0\0\x1\x89\0\0\x1\x9c\0\0\x1\n\0\xff\xff\xff\xff\x1\0\0\0\x1\0)

[style]
showUnbreakableSpace=true
